services:
  tasksync:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These values will be picked up from your .env file by Docker Compose
        - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
        - GOOGLE_SHEET_NAME=${GOOGLE_SHEET_NAME}
        - GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_JSON=${GOOGLE_SERVICE_ACCOUNT_CREDENTIALS_JSON}
        - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
        - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}
    ports:
      - '5173:5173'
    env_file:
      - .env
    environment:
      - PORT=5173 # You can override or set additional environment variables here
    restart: unless-stopped

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
